name: Starter Workflow Demo
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: demo workflow job
        run: echo This is a demo start workflow
        
      - name: Install updates
        run: sudo apt update

      - name: Install GCC
        run: sudo apt-get install gcc
      
      - name: Make obj puzzle
        run: gcc *.c *.h -o puzzle
      
      - name: Run prog
        run: ./puzzle 2 1 2 4 2 3 3 1 2 3 1 2 3 2 2 1 | tee log1
        
        
      - name: Run prog
        run: ./puzzle 2 1 2 4 2 3 3 1 3 2 2 1 2 3 1 2 | tee log2
        
        
      - name: Run prog
        run: ./puzzle 2 1 2 4 2 3 1 2 2 3 3 1 3 2 2 1 | tee log3
        
        
      - name: Run prog
        run: ./puzzle 2 3 3 1 2 3 1 2 3 2 2 1 2 1 2 4 | tee log4
        
      - name: Print results
        run: echo lo1; echo log2, echo log3, echo log4
