name: Workflow demo
on:
  push:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Insert 16 digits in brackets'
        # Default value if no value is explicitly provided
        default: 'INPUT VARIABLES'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Install updates, GCC -> compile
        run: sudo apt update; sudo apt-get install gcc; gcc *.c *.h -o puzzle

      - name: Run with Github inputs
        run: echo; ./puzzle "${{ github.event.inputs.name }}"; echo


#       - name: Run prog OK
#         run: ./puzzle "2 3 3 1 3 2 1 3 2 1 2 3 1 2 3 2"  |  tee log0
        
        
#       - name: Run prog ERROR n>4
#         run: ./puzzle "2 3 3 1 3 2 1 3 2 1 2 3 1 2 2 21"  | tee log1
        
        
#       - name: Run prog ERROR argc>2
#         run: ./puzzle "2 1 2 4 2 3 1 2 2 " "3 3 1 3 2 2 1" | tee log2
        
#       - name: Run prog ERROR argc=1
#         run: ./puzzle | tee log3
        
#       - name: Run prog ERROR argv[1][n] < 16
#         run: ./puzzle "2 3 3 1 3 2 1 3 2 1 2 2" | tee log4
        
#       - name: Print results
#         run: cat log0; echo; cat log1; cat log2; cat log3; cat log4
